# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFNetworkingHttps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AFNetworkingHttps

pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD'


  target 'AFNetworkingHttpsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFNetworkingHttpsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
